// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class AhorradoresBancario
{
    public int? IdAhorrador { get; set; }

    public int Folio { get; set; }

    public string Clabe { get; set; }

    public string Institucion { get; set; }

    public string Plaza { get; set; }

    public string Cuenta { get; set; }
}