// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class Ahorradore
{
    public int Id { get; set; }

    public long Folio { get; set; }

    public string NPersonal { get; set; }

    public string Paterno { get; set; }

    public string Materno { get; set; }

    public string Nombres { get; set; }

    public string Correo { get; set; }

    public string Usuario { get; set; }

    public string Secreto { get; set; }

    public string TelMovil { get; set; }

    public string TelFijo { get; set; }

    public string UaTime { get; set; }

    public string UaIp { get; set; }

    public string UaHost { get; set; }

    /// <summary>
    /// C= Cliente; A=Administrativo
    /// </summary>
    public string Tipo { get; set; }

    public string Estado { get; set; }

    public string Aprobado { get; set; }
}