// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class AsistenciasDispositivo
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Serie { get; set; }

    public string Direccion { get; set; }

    public string Puerto { get; set; }

    public string Info { get; set; }
}