// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class AsistenciasRegistro
{
    public string IdChecador { get; set; }

    public string Tipo { get; set; }

    public string Fecha { get; set; }

    public string Hora { get; set; }
}