// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class AsistenciasEmpleado
{
    public string IdNominas { get; set; }

    public int IdChecador { get; set; }

    public int IdEmpresa { get; set; }

    public string Nombre { get; set; }
}