// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class BecasMe
{
    public int IdMes { get; set; }

    public int? NBecas { get; set; }
}