// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class BecasPeriodo
{
    public string Id { get; set; }

    public DateTime? FInicio { get; set; }

    public DateTime? FFinal { get; set; }

    public string Estado { get; set; }
}