// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class BecasEmpleado
{
    public string Matricula { get; set; }

    /// <summary>
    /// Id del comedor que tiene asignado
    /// </summary>
    public int? IdComedor { get; set; }

    public string Nombre { get; set; }

    /// <summary>
    /// clave de acceso a calemdario de alimentos
    /// </summary>
    public string Secreto { get; set; }

    /// <summary>
    /// Numero de alimentos autorizados en el periodo
    /// </summary>
    public int? NAlimentos { get; set; }

    /// <summary>
    /// Dependencia que beca al alumno
    /// </summary>
    public string Dependencia { get; set; }

    /// <summary>
    /// Región de aplicación
    /// </summary>
    public string Region { get; set; }

    /// <summary>
    /// Correo electronico institucional
    /// </summary>
    public string Correo { get; set; }

    /// <summary>
    /// Bandera de programación de calendario
    /// </summary>
    public int? Calendarizo { get; set; }

    /// <summary>
    /// A Activo, I Inactivo
    /// </summary>
    public string Estado { get; set; }

    /// <summary>
    /// Indice derecho
    /// </summary>
    public string Huella1 { get; set; }

    /// <summary>
    /// Indice Izquierdo
    /// </summary>
    public string Huella2 { get; set; }

    /// <summary>
    /// Recibe a cualquier hora
    /// </summary>
    public string HorarioAbierto { get; set; }
}