// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class CarrerasNumero
{
    public string Region { get; set; }

    public int? Numero { get; set; }
}