// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class CarrerasParticipante
{
    public int Id { get; set; }

    public int NumCorredor { get; set; }

    public string Nombre { get; set; }

    public string Matricula { get; set; }

    public DateTime? Nacimiento { get; set; }

    public string Correo { get; set; }

    public int? Cp { get; set; }

    public string Ciudad { get; set; }

    public string Estado { get; set; }

    public string Pais { get; set; }

    public long? Telefono { get; set; }

    public long? TelefonoEmergencia { get; set; }

    public string Categoria { get; set; }

    public string Rama { get; set; }

    public string Longitud { get; set; }

    public string Region { get; set; }

    public string Talla { get; set; }

    public string Equipo { get; set; }

    public string FolioRegion { get; set; }

    public string Discapacidad { get; set; }

    public string Registro { get; set; }

    public string Mail { get; set; }
}