// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class ClavesSolicitud
{
    /// <summary>
    /// Tiempo de solicitud
    /// </summary>
    public string TimeRequest { get; set; }

    /// <summary>
    /// Código hash de solicitud
    /// </summary>
    public string Hash { get; set; }

    /// <summary>
    /// Número de whatsapp
    /// </summary>
    public string WhatsappNumber { get; set; }

    /// <summary>
    /// Correo del usuario
    /// </summary>
    public string MailUser { get; set; }

    /// <summary>
    /// Nuevo correo al cambiar
    /// </summary>
    public string NewMail { get; set; }

    /// <summary>
    /// Modulo que usa el cambio
    /// </summary>
    public string ModOrigen { get; set; }
}