// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

/// <summary>
/// Catálogo para los códigos postales en las direcciones.
/// </summary>
public partial class CPostal
{
    public int Cp { get; set; }

    public string Asentamiento { get; set; }

    public string Tipo { get; set; }

    public string Municipio { get; set; }

    public string Estado { get; set; }

    public string Ciudad { get; set; }

    public string Zona { get; set; }
}