// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class Folio
{
    public int Id { get; set; }

    public string Concepto { get; set; }

    public string Serie { get; set; }

    public int? Folio1 { get; set; }
}