// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class NominaHuella
{
    public int IdChecador { get; set; }

    public string Fp00 { get; set; }

    public string Fp01 { get; set; }

    public string Fp02 { get; set; }

    public string Fp03 { get; set; }

    public string Fp04 { get; set; }

    public string Fp05 { get; set; }

    public string Fp06 { get; set; }

    public string Fp07 { get; set; }

    public string Fp08 { get; set; }

    public string Fp09 { get; set; }

    public string Fp10 { get; set; }
}