// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class NominaEmpresa
{
    public int IdEmpresa { get; set; }

    public string NombreEmpresa { get; set; }

    public string DbName { get; set; }
}