// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class TpvCaja
{
    public int Id { get; set; }

    /// <summary>
    /// Usuario que tiene asignada la caja
    /// </summary>
    public int IdUsuario { get; set; }

    /// <summary>
    /// Nombre de la caja
    /// </summary>
    public string Nombre { get; set; }

    /// <summary>
    /// Nombre de la empresa comercial
    /// </summary>
    public string EmpresaSdk { get; set; }

    /// <summary>
    /// Código de concepto para documentos
    /// </summary>
    public string ConceptoSdk { get; set; }

    /// <summary>
    /// Código de concepto para becas comedores
    /// </summary>
    public string BecasSdk { get; set; }

    /// <summary>
    /// Código de concepto para abonados comedores
    /// </summary>
    public string AbonadosSdk { get; set; }

    /// <summary>
    /// Código de concepto para alimentos de empleados
    /// </summary>
    public string EmpleadosSdk { get; set; }

    /// <summary>
    /// Software para la impresión
    /// </summary>
    public string PrintSoft { get; set; }

    /// <summary>
    /// Nombre de la impresora
    /// </summary>
    public string PrintName { get; set; }

    /// <summary>
    /// Imagen en color de la empresa
    /// </summary>
    public int? ImgColor { get; set; }

    /// <summary>
    /// Correos de notificacion
    /// </summary>
    public string MailNotify { get; set; }

    /// <summary>
    /// Horario de ventas abierto
    /// </summary>
    public string HorarioAbierto { get; set; }
}