// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class TpvCajasAlmacene
{
    /// <summary>
    /// id de la caja
    /// </summary>
    public int? IdCaja { get; set; }

    /// <summary>
    /// id almacen en ContPAQ
    /// </summary>
    public string IdSdk { get; set; }

    /// <summary>
    /// nombre almacen en ContPAQ
    /// </summary>
    public string NombreSdk { get; set; }
}