// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class TpvOrdenesPago
{
    public int Id { get; set; }

    /// <summary>
    /// Sistema donde se originó la orden
    /// </summary>
    public string SistemaEmisor { get; set; }

    /// <summary>
    /// Sistema en el que se recibe el pago
    /// </summary>
    public string SistemaReceptor { get; set; }

    /// <summary>
    /// Referencia de la orden de pago
    /// </summary>
    public string IdReferencia { get; set; }

    /// <summary>
    /// Referencia banamex asignada
    /// </summary>
    public string IdRefBanamex { get; set; }

    /// <summary>
    /// Id del participante asociado
    /// </summary>
    public int IdParticipante { get; set; }

    /// <summary>
    /// Tiempo de generacion de orden
    /// </summary>
    public long TiempoCreacion { get; set; }

    /// <summary>
    /// Tiempo limite de pago
    /// </summary>
    public long? TiempoLimite { get; set; }

    /// <summary>
    /// Tiempo en el que se recibió el pago
    /// </summary>
    public long? TiempoPago { get; set; }

    /// <summary>
    /// Monto a pagar
    /// </summary>
    public double Monto { get; set; }

    /// <summary>
    /// Concepto de pago
    /// </summary>
    public string Concepto { get; set; }

    /// <summary>
    /// Estado de la Orden
    /// </summary>
    public string Estado { get; set; }

    public int? Aviso { get; set; }
}