// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class TpvRefBanamex
{
    public int Id { get; set; }

    public string Suc { get; set; }

    public string Cta { get; set; }

    public string Alfanumerica { get; set; }

    public string AlfanumericaDv { get; set; }

    public string Estado { get; set; }
}