// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class TpvUsuario
{
    public int Id { get; set; }

    public string Paterno { get; set; }

    public string Materno { get; set; }

    public string Nombres { get; set; }

    public string Usuario { get; set; }

    /// <summary>
    /// (A)dministrador (S)upervisor (V)endedor
    /// </summary>
    public string Tipo { get; set; }

    /// <summary>
    /// Contraseña
    /// </summary>
    public string Pass { get; set; }

    public string Huella1 { get; set; }

    public string Huella2 { get; set; }

    public string AccesoFecha { get; set; }

    public string AccesoHora { get; set; }

    /// <summary>
    /// (A)ctivo (I)nactivo
    /// </summary>
    public string Estado { get; set; }
}