// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class TpvVentasAux
{
    public int Id { get; set; }

    public int IdVenta { get; set; }

    /// <summary>
    /// R_regular D_donativo
    /// </summary>
    public string Tipo { get; set; }

    public int Cantidad { get; set; }

    public string Codigo { get; set; }

    public string Producto { get; set; }

    public string Catacteristicas { get; set; }

    public string Almacen { get; set; }

    public float Precio { get; set; }

    public int? Descuento { get; set; }

    public float Total { get; set; }
}