// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class UsuariosEmpresa
{
    /// <summary>
    /// id del acceso
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// id del usuario
    /// </summary>
    public int IdUsuario { get; set; }

    /// <summary>
    /// id de la empresa
    /// </summary>
    public string OpEmpresas { get; set; }
}