// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TpvEmpresasUV.modelos;

public partial class Usuario
{
    public int Id { get; set; }

    public string Correo { get; set; }

    public string Paterno { get; set; }

    public string Materno { get; set; }

    public string Nombre { get; set; }

    public int? TelMovil { get; set; }

    public string Usuario1 { get; set; }

    public string Secreto { get; set; }

    public string UaTime { get; set; }

    public string UaIp { get; set; }

    public string UaHost { get; set; }

    public string Estado { get; set; }
}